import Img1 from './Images/cileni.svg';
import Img2 from './Images/cileni.svg';
import Img3 from './Images/cileni.svg';

const DummyGroups = [
  {
    _id: '1',
    name: 'Anto Ramadhan',
    bio: 'hai anto, saya owner butik dari',
    pic: Img1,
    members: ['Shivam', 'Vishal', 'Kunj', 'Barbox', 'Zeemon'],
    rooms: [
      'general',
      'announcements',
      'meetup',
      'random',
      'music',
      'gaming',
      'memes',
      'programming',
      'art',
      'movies',
      'books',
    ],
  },
  {
    _id: '2',
    name: 'Ruben Siahaan',
    bio: 'Halo, terimakasih telah mengirim',
    pic: Img2,
    members: ['Shivam', 'Vishal', 'Kunj'],
    rooms: [
      'general-anime',
      'new-releases',
      'popular-series',
      'manga-discussion',
      'anime-recommendations',
      'fan-art',
      'cosplay',
      'anime-music',
      'voice-acting',
      'conventions',
      'anime-theory',
      'memes',
      'spoilers',
    ],
  },
  {
    _id: '3',
    name: 'Sindi Amanda',
    bio: 'jalo, saya tertarik',
    pic: Img3,
    members: ['Shivam', 'Vishal', 'Kunj', 'Barbox'],
    rooms: [
      'general',
      'announcements',
      'random',
      'music',
      'gaming',
      'memes',
      'programming',
      'art',
      'movies',
      'books',
      'science',
      'food',
      'sports',
      'fashion',
      'travel',
      'technology',
      'news',
      'politics',
      'pets',
      'photography',
    ],
  },
];

export default DummyGroups;
